<?php
$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);
return [
    'phpseclib\\' => [$vendorDir . '/phpseclib/phpseclib/phpseclib'],
    'Zend\\Validator\\' => [$vendorDir . '/zendframework/zend-validator/src'],
    'Zend\\Uri\\' => [$vendorDir . '/zendframework/zend-uri/src'],
    'Zend\\Stdlib\\' => [$vendorDir . '/zendframework/zend-stdlib/src'],
    'Zend\\Math\\' => [$vendorDir . '/zendframework/zend-math/src'],
    'Zend\\Loader\\' => [$vendorDir . '/zendframework/zend-loader/src'],
    'Zend\\Json\\' => [$vendorDir . '/zendframework/zend-json/src'],
    'Zend\\Http\\' => [$vendorDir . '/zendframework/zend-http/src'],
    'Zend\\Escaper\\' => [$vendorDir . '/zendframework/zend-escaper/src'],
    'Zend\\Crypt\\' => [$vendorDir . '/zendframework/zend-crypt/src'],
    'ZendXml\\' => [$vendorDir . '/zendframework/zendxml/src'],
    'ZendService\\Amazon\\' => [$vendorDir . '/zendframework/zendservice-amazon/src'],
    'Twig\\' => [$vendorDir . '/twig/twig/src'],
    'Tests\\' => [$baseDir . '/tests'],
    'Symfony\\Polyfill\\Ctype\\' => [$vendorDir . '/symfony/polyfill-ctype'],
    'Psr\\Log\\' => [$vendorDir . '/psr/log/Psr/Log'],
    'Psr\\Http\\Message\\' => [$vendorDir . '/psr/http-message/src'],
    'Psr\\Container\\' => [$vendorDir . '/psr/container/src'],
    'Psr\\Cache\\' => [$vendorDir . '/psr/cache/src'],
    'Pg\\' => [$baseDir . '/includes/Pg'],
    'Monolog\\' => [$vendorDir . '/monolog/monolog/src/Monolog'],
    'Interop\\Container\\' => [$vendorDir . '/container-interop/container-interop/src/Interop/Container'],
    'GuzzleHttp\\Psr7\\' => [$vendorDir . '/guzzlehttp/psr7/src'],
    'GuzzleHttp\\Promise\\' => [$vendorDir . '/guzzlehttp/promises/src'],
    'GuzzleHttp\\' => [$vendorDir . '/guzzlehttp/guzzle/src'],
    'Google\\Auth\\' => [$vendorDir . '/google/auth/src'],
    'Firebase\\JWT\\' => [$vendorDir . '/firebase/php-jwt/src'],
    'Ec\\' => [$baseDir . '/includes/Ec'],
    'Doctrine\\Common\\Cache\\' => [$vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'],
    'DTS\\eBaySDK\\' => [$vendorDir . '/dts/ebay-sdk-php/src'],
];
